### PR TITLE
allow plugins to depend on one another (breaking change)

### PR DESCRIPTION
**Pull request by andyroyle**
- deps must be static and exposed as an array of plugin names, e.g. `module.exports.dependencies = ['myplugin', 'myotherplugin']`
- will detect circular dependencies and missing plugins
- registers each plugin only when all it's dependencies have been registered
- recursively registers in cases of deep dependency chains
- passes dependencies as an object to the register method (e.g. use `deps.myplugin()` to execute the dep)

Adds an extra module dep [madge](https://github.com/pahen/madge), which seems pretty heavy (for the tiny piece we're using (checking for circular dependencies).

Not sure if it's worth finding an alternative or just pulling the logic out and wrapping it in a new package.

See what you think @matteofigus.

### CODE REVIEW

**Comment by matteofigus** [comment]
:+1: Thanks good job! I would leave the madge optimisation in the future in case.
Just give me some time to look at the PR - it's a lot of code.

PS
madge depends on coffeescript because of Gruntfile.coffee
ok

**Comment by andyroyle** [comment]
actually, fuck madge, I'm going to swap it out for this: https://www.npmjs.com/package/dependency-graph

**Comment by matteofigus** [comment]
`dependencies": {}` :beers:

**Comment by andyroyle** [comment]
closes #128

**Comment by andyroyle** [comment]
@matteofigus you had a chance to look at this one?

**Comment by matteofigus** [comment]
Published `0.20.0`

**Pull request merged**
