### PR TITLE
Fix for #391 - support pre-release versions of components

### PR DESCRIPTION
**Pull request by BhautikDoshi**
#391

### CODE REVIEW

**Comment by matteofigus** [comment]
This is failing on linux because of the module missing from the shrinkwrap. I'll see if I can update the PR with the fix during today.

**Comment by matteofigus** [comment]
Made a PR: https://github.com/BhautikDoshi/oc/pull/1

**Comment by matteofigus** [comment]
Thanks for taking care of this @BhautikDoshi - this is out on latest version.

**Comment by BhautikDoshi** [comment]
Thanks @matteofigus. Will move to 0.36.3.

**Pull request merged**
