### PR TITLE
[DX-247] dev/publish cli mode - prevent some deps to run in an infinite loop

### LINKED ISSUE #730: oc-client 0.41.15 does not properly compile some dependencies
Today I've found our CI environment failing on OC deploy, due to the following error:

imatge

We didn't change anything from the previous working deploy to this, but the oc-client version changed. Using oc-client 0.41.13 works as expected, but the current doesn't allow us to properly publish to the registry.

### PR DESCRIPTION
**Pull request by matteofigus**
Fixes #730

### CODE REVIEW

**Comment by elboletaire** [comment]
Sorry to ask this twice, but apparently my first comment went unnoticed. Could it be possible to add some cli arg to avoid checking for dependencies? This is something we already do always before pushing to the registry, so oc makes it redundant and tries to do something that has been recently done. In our side would have much sense to be able to disable this.

/cc @nickbalestra @matteofigus

**Comment by nickbalestra** [comment]
I wouldn't be against a flag to skip packaging for the `publish`. Will you be up to attempt a PR for this? Happy to help if you need

**Comment by elboletaire** [comment]
Yeah ofc @nickbalestra. For the moment I'll open it, and if I have time I'll try to do something, but the main problem is the time, you know... 😅

**Comment by nickbalestra** [comment]
Awesome. Time...I know 😅 , no rush and keep me posted

**Comment by elboletaire** [comment]
btw created #769 as a follow-up

**Pull request merged**
