### PR TITLE
Issue #379 support for minio

### PR DESCRIPTION
**Pull request by kmcrawford**
Add support for minio via endpoint s3 config.

Example:

endpoint: 'http://minio.local:9000',
    path: 'http://minio.local:9000/oc-registry/',
    s3ForcePathStyle: 'true',
    signatureVersion: 'v4',

### CODE REVIEW

**Comment by kmcrawford** [comment]
I am closing this since I misunderstood that nearly everything on s3 is public except server.js.  This complicates things and does add security risks.  Minio only has the ability to mark directories as public/private and not individual files.

**Comment by matteofigus** [comment]
Correct. I don't know minio a lot, but perhaps if you put a cdn on top of it or some sort of proxy, you can add a rule to block server.js to be publicly served?

**Comment by kmcrawford** [comment]
I have figured out how to set file level permissions via minio using bucket policy.  Essentially it will create a resource like below for everything that needs to be public.  The only issue there is a bug with their setBucketPolicy api, where it wipes out the current bucket policy and unable to append.  I spoke to the staff an minio and they said they will fix this next week.  I nearly had this all working locally till I found this bug, so once they fix I can create a new PR that will support this.

I know it's not perfect creating an * on the end of the resource, but since the extension is included it should be unique.

https://github.com/minio/minio-js/issues/618

{
		"Sid": "",
		"Effect": "Allow",
		"Principal": {
			"AWS": ["*"]
		},
		"Action": ["s3:GetObject"],
		"Resource": ["arn:aws:s3:::registry/components/oc-client/0.41.5/template.js*"]
	},

**Comment by matteofigus** [comment]
Fantastic, great job

**Pull request closed without merging**
