### PR TITLE
Updated instructions of how to add static resource to the file

### PR DESCRIPTION
**Pull request by jankowiakmaria**
I've renamed the static resource dir to avoid confusion.

#airportCoding

### CODE REVIEW

**Comment by matteofigus** [comment]
✈️

**Comment by mattiaerre** [comment]
hi @jankowiakmaria and @matteofigus 
I was thinking that while you are "dealing" w/ this it would be nice to have the static folder in the example named as "public" rather than "src" which, in my opinion, looks like more the folder containing all the source code of a component. The name "public" on the other hand, is used by other web application frameworks such as [express](http://expressjs.com/en/starter/generator.html) in order to expose static assets such as javascript and css files.
what do you think?
thanks,
-Mattia

**Comment by jankowiakmaria** [comment]
Makes sense for me 👍

**Comment by mattiaerre** [comment]
thanks @matteofigus and @jankowiakmaria please reopen your branch and change the name then 😉 
-Mattia

**Pull request merged**
