### PR TITLE
Replace jshint by eslint

### PR DESCRIPTION
**Pull request by elboletaire**
I'm creating the PR as a WIP because I'm currently working on it and I see things which create some questions for me:

- I get a lot of `no-undef` errors due to the injected libraries (under testing, the `it` and `describe`, more specifically). I've currently switch the rule to show warnings instead of errors, but I think it's better to disable it adding `/* eslint no-undef: 'off' */` for each test file that brings an error. If you're ok with it, I'll do a commit re-enabling the rule and setting the rule file by file.
- I've set `no-console` to `warn`. Would you like to set it to off, or is it ok to stay as warnings?

I'll also try to edit this post to add some notes about some decisions I made:

- The first commit is just the automatically created file from `eslint --init`. There are a lot of rules set to `off` that you may want to check.
- I've set `no-extra-boolean-cast` to `warn` in order to change from errors to warnings, so you don't forget about it :p
- I've set `no-empty` with` "allowEmptyCatch": true`, to allow empty `catch` statements.
- As there's no option for setting the `.eslintignore` file as a [`grunt-eslint`][grunt-eslint] parameter, I've decided to move both `.eslintrc.json` and `.eslintignore` to the root path, and remove the `tasks/support` folder, which was containing the `.jshintrc` file.
- We should consider changing the [`strict`][strict] rules, as they're not needed for nodejs modules (they're in strict mode by default).

refs #436

[grunt-eslint]: https://github.com/sindresorhus/grunt-eslint
[strict]: http://eslint.org/docs/rules/strict

### CODE REVIEW

**Comment by matteofigus** [comment]
I've read your mind before so opened https://github.com/opentable/oc/pull/449 💃

**Comment by elboletaire** [comment]
haha did not see it :p

Then I'll merge my branch with master when your PR is accepted. I remove that question from the PR, but please, try to answer the other ones too 😃

**Comment by elboletaire** [comment]
Added note:

> - As there's no option for setting the `.eslintignore` file as a [`grunt-eslint`][grunt-eslint] parameter, I've decided to move both `.eslintrc.json` and `.eslintignore` to the root path, and remove the `tasks/support` folder, which was containing the `.jshintrc` file.

[grunt-eslint]: https://github.com/sindresorhus/grunt-eslint

**Comment by elboletaire** [comment]
I've removed the `WIP` because my work is done until you answer that two questions in the PR 😃 

Tests run perfect locally, but for some reason have not been executed in travis nor in appveyor.

**Comment by elboletaire** [comment]
PS. Merging with master, as #449 has been merged

**Comment by elboletaire** [comment]
Added:

> - We should consider changing the [`strict`][strict] rules, as they're not needed for nodejs modules (they're in strict mode by default).

[strict]: http://eslint.org/docs/rules/strict

**Comment by elboletaire** [comment]
Merged with master and fixed `no-unused-vars` issues appeared after enabling the rule again.

Note that I've set `no-unused-vars: 'off'` in [`registry-domain-components-cache.js`][registry-domain-components-cache.js] because there's giving a false positive (apparently does not properly detect the scope of the `response` var).

[registry-domain-components-cache.js]: https://github.com/elboletaire/oc/blob/ef81c2422bd1da17c1489ba8391b0ef7af86b89b/test/unit/registry-domain-components-cache.js#L2

**Comment by matteofigus** [comment]
This looks good to me for now. Let's create separate issues for each rule that we may want to change. Agree about the no-strict, in case let's make a different PR for that.

Thanks for working on this!

**Pull request merged**
