### PR TITLE
Node 8

### PR DESCRIPTION
**Pull request by matteofigus**
🎉 🎈 😃

### CODE REVIEW

**Comment by matteofigus** [comment]
Looks like 🔴 because of npm install. 
Let's keep it opened and will try to reproduce locally

**Comment by diffalot** [comment]
I have been able to reproduce this.

https://github.com/opentable/oc/blob/master/npm-shrinkwrap.json#L5066-L5070

it turns out that npm 3.10.8 has a dependency on asap that resolves to an uber internal registry, and installing on node 6 with npm 3.10.10 works fine, but installing with node 8 and npm 5 does not work.

I'm not sure what the path past this is, it may be resolved by #404 or perhaps a upgrade to a newer npm version is safe to do?

running `npm install --save npm` seems to get around the error

**Comment by matteofigus** [comment]
Thanks for digging into this @diffalot, perhaps a quick upgrade to latest npm could do the job 👍

**Comment by mattiaerre** [comment]
shall we do something like:

```yaml
before_install:
  - "npm install -g npm@5"
```

in the .travis.yml file?

**Comment by matteofigus** [comment]
@mattiaerre I think the issue is not to the npm used for the install, but the npm used as dependency in the registry. I will update that asap and it should fix. Leave it to me ;)

**Comment by matteofigus** [comment]
Closing this. Will reopen after I get it green locally and after merging #497

**Pull request closed without merging**
