### PR TITLE
Node 6

### PR DESCRIPTION
**Pull request by matteofigus**

### CODE REVIEW

**Comment by matteofigus** [comment]
:(

**Comment by matteofigus** [comment]
Looks like upgrading necessary dependencies for making node 6 happy brakes all the sauce labs stuff.

**Comment by ArnoldZokas** [comment]
Too early for node 6, IMO. Do you want to keep this PR open or close it (but keep the branch)?

**Comment by matteofigus** [comment]
Ok I'll keep the branch.

**Pull request closed without merging**
