### PR TITLE
Removing info, ls, link, unlink

### LINKED ISSUE #146: Remove old stuff
Looks like some stuff was a good idea at the beginning, not sure we really need some stuff anymore:

- [x] oc link (as consumer, you do oc link header@1.2.3 to add it to local oc.json file)
- [x] oc unlink (as consumer, you remove the linked component from oc.json file)
- [x] oc info (to see info about a linked component and in case suggest upgrade)
- [x] oc ls (to see all components for linked registry - we have the web interface now for that)

So, democratically, I am gonna ask top 4 contributors and my vote is gonna be counted only if is gonna be a tie. Please vote for each one until Friday night replying here for keeping or killing each one of those functionalities.

@jankowiakmaria @andyroyle @federicomaffei @tpgmartin

### PR DESCRIPTION
**Pull request by matteofigus**
Fixes #146

### CODE REVIEW

**Comment by andyroyle** [comment]
:+1:

**Comment by andyroyle** [comment]
@matteofigus want me to publish this as a breaking change?

**Comment by matteofigus** [comment]
Yeah, thanks

**Comment by andyroyle** [comment]
published 0.21.0

**Pull request merged**
