### PR TITLE
publish to all the registries listed in oc.json

### PR DESCRIPTION
**Pull request by andyroyle**
Run async.eachSeries over the list of registry urls and publish the package to each one.

Currently it ignores any errors (lets the logger print them to the console), and continues publishing even if a previous publish failed.

### CODE REVIEW

**Comment by andyroyle** [comment]
also ah feck just realised that i pushed to opentable, rather than my fork. DOH!

**Comment by matteofigus** [comment]
No worries, just put a `don't merge` on the title and I'll keep it there until you are happy with it

**Comment by andyroyle** [comment]
this is good to go, just as soon as I work out why the tests are failing

**Comment by matteofigus** [comment]
Looks like SauceLabs is having troubles - re-pushed the button.

**Comment by matteofigus** [comment]
I tried to make some experiments to stabilise SauceLabs. if you take the latest changes from the master, we can have another go and see if it goes green @andyroyle ? Thanks

**Comment by andyroyle** [comment]
rebased, lets see if it works this time

**Comment by matteofigus** [comment]
Ah, apparently Travis doesn't correctly use proper credentials when using encrypted environment variables coming from forks. I made you admin, next time just create a new branch here :+1:

**Pull request merged**
