### PR TITLE
js.gz + css.gz handling

### PR DESCRIPTION
**Pull request by matteofigus**
This should be the first part of #138 

Basically, when static folder contains files with `.css.gz` or `js.gz` extensions, 
* oc dev watcher handles it (forwards to the client a `Content-Encoding:gzip` header for given resource)
* s3 publish should save the ContentEncoding property to the S3 object (so that Cloudfront should recognise it and forward it)

### CODE REVIEW

**Comment by matteofigus** [comment]
Can you review @andyroyle ?

**Comment by andyroyle** [comment]
makes sense to me

**Comment by andyroyle** [comment]
published 0.20.5

**Comment by matteofigus** [comment]
:+1:

**Pull request merged**
