### PR TITLE
Publish bugfix

### PR DESCRIPTION
**Pull request by seif**
Publishing is broken for us. Seems to be introduced in https://github.com/opentable/oc/pull/401/files#diff-a2e63764c6a11da37d72c74c84108e0dL15

### CODE REVIEW

**Comment by seif** [comment]
@matteofigus @nickbalestra @ArnoldZokas this is blocking our deploys. can you prioritise please!

**Comment by matteofigus** [comment]
@seif on it.

**Comment by matteofigus** [comment]
This causes https://github.com/mattiaerre/oc-hub/issues/2

**Comment by seif** [comment]
@matteofigus this was not reproducable on 0.36.1, only in 0.36.2 so I don't think it will fix mattiaerre/oc-hub#2

**Comment by seif** [comment]
thanks @matteofigus

**Comment by matteofigus** [comment]
Oh thanks you're right about @mattiaerre's, I confused 0.36.1 with 0.36.0. BTW this is now out with 0.36.4 - thanks for the fix!

**Pull request merged**
